### PR TITLE
Adding clitic lemma and gramm

### PR DESCRIPTION
**Pull request by fmatter**
Currently, using clitics.txt lines [743-748](https://github.com/timarkh/uniparser-morph/blob/master/uniparser_morph/morph_parser.py#L743-L748) raise errors like the following:

```
wf.add_to_field('lemma', cl.lemma)
AttributeError: 'Wordform' object has no attribute 'add_to_field'
```

I fixed these uses of `add_to_field` to `add_lemma`, `add_gramm` and `add_other_data`. I also made sure that the `lex` and `gramm` value of clitics are properly added to the word form. If the clitic's `lex` field should not be added to the wordform's lemma, it can be left empty. So if one considers a clitic to be a lexeme of its own, then one can add the lemma, but that is not necessary.

I think this should not break any functionality, but I can of course not be sure :)

### CODE REVIEW

**Comment by fmatter** [comment]
Note that I am getting a `Wrong lemma: ""` error when leaving the `lex` field of the clitic empty (in order to not make it show in the lemma). If the `lex` field has a value, there are no errors.

**Comment by fmatter** [comment]
Here is a MWE showing the implemented functionality: [uniparser_mwe_clitic.zip](https://github.com/timarkh/uniparser-morph/files/8304014/uniparser_mwe_clitic.zip)

The `lex` field of the single clitic can be filled, making it appear in the (now comma-separated) lemma (list).

**Comment by fmatter** [comment]
Also, I just noticed that clitic stacking -- i.e., multiple subsequent clitics -- does not appear to work. Did it ever work? If so, did my changes break something? If not: I think clitic stacking is not uncommon at all.

If it is indeed too much work to bring the code for clitics back up to speed -- and allow clitic stacking -- I have an alternative suggestion: Since the difference in the output boils down to "what separators are used in the `gloss` field", why not allow affixes to define their own separator, overriding default `-`?

**Review by timarkh — APPROVED** [review]
That makes sense, thanks! The only thing I'll change is replacing a comma with a plus sign for combining the clitic's lemma with the host's lemma (I'm already using + for that elsewhere). I have not used the clitics part myself for a long time, which is probably why it got outdated without me noticing.

**Comment by fmatter** [comment]
> That makes sense, thanks! The only thing I'll change is replacing a comma with a plus sign for combining the clitic's lemma with the host's lemma (I'm already using + for that elsewhere). I have not used the clitics part myself for a long time, which is probably why it got outdated without me noticing.

Ah, that's where this happened...

Am I correct in assuming that the other place you use `+` is for lemmata derived via something defined in `derivations.txt`? Because if so, I think it is an unfortunate choice to also use it for clitics...

* *lexeme-form=clitic*: `lexeme+clitic`
* *lexeme-derivation*: `lexeme+derivation`

how can I distinguish these two scenarios?

**Comment by fmatter** [comment]
I would choose the comma all over again -- grammatical tags are separated by commas, why should lexemes not be separated by commas?

**Pull request merged**
